# Generated by Django 5.0.6 on 2024-07-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_tag_article_article_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
