# Generated by Django 5.0.6 on 2024-07-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_image_caption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='categories',
        ),
    ]
