# Generated by Django 5.0.6 on 2024-07-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_tag_category_rename_tags_article_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
